### ISSUE TITLE
Identify GH Authenticated Username's Affiliated Organizations and Projects

### ISSUE THREAD

**Issue by kylemann** [buildwithline/line#2]
## Problem to solve

**Context**: In a previous pull request ([#1](https://github.com/buildwithline/line/pull/1)), GitHub login authentication was added to the Line application.

The next step is to identify the authenticated GitHub username related organizations and projects they are affiliated with, along with specifying their role within those entities (e.g., member, admin, owner).

The primary objective is to authenticate user affiliations with projects and organizations. This authentication will enable users to qualify for and select projects or organizations for fundraising purposes. You can view a walkthrough of this feature in action [here](https://www.youtube.com/watch?v=LL-5hnCAcBY&ab_channel=Line%E2%80%93TheDevelopersMarketplace).

## Solution

1. Per the Authenticated user's GitHub username, then utilize the GitHub API to identify the organizations and projects associated with the authenticated user.
2. Retrieve and display the user's related roles within these organizations and projects in the UI.
     - ability to choose organization
     - once organization is chose, show related projects + usernames role (member, admin, owner, etc) 

Next steps will be:

1. UI/UX
2. Ability for user to select organization and/or project
3. Once selected org/project ability to initiate fundraising

**Comment by codersquirrelbln** [comment]
Thanks for the summary and structure, that's very helpful! Could you please add some screenshots of designs here, so one doesn't have to go back to the video to consult? Useful to have the visuals here 🙏
